version: '2'
services:
  web:
    image: whyour/qinglong:latest
    volumes:
      - /ql/config
      - /ql/log
      - /ql/db
      - /ql/scripts
      - /ql/repo
      - /ql/raw
    ports:
      - "5700:5700"
    restart: unless-stopped
